name: widget-test

on: [push]

jobs:
  widget-test:
    name: Run Widget Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: Run Widget Test
        working-directory: ./frontend
        run: flutter test
